support coming triton 3.4.0

diff --git a/.github/workflows/triton-nightly.yml b/.github/workflows/triton-nightly.yml
--- a/.github/workflows/triton-nightly.yml
+++ b/.github/workflows/triton-nightly.yml
@@ -68,11 +68,17 @@ jobs:
         if: ${{ steps.check-version.outputs.new_commit == 'true' }}
         working-directory: triton
         run: |
-            # Replace the URL using sed
-            sed -i 's|https://oaitriton.blob.core.windows.net/public/llvm-builds/|https://llvm.fla-org.com/|g' python/setup.py
-
-            # Verify the change (optional)
-            grep "llvm.fla-org.com" python/setup.py || (echo "URL replacement failed"; exit 1)
+          if [ -f "python/setup.py" ]; then
+            file_path="python/setup.py"
+          elif [ -f "setup.py" ]; then
+            file_path="setup.py"
+          else
+            echo "Error: Neither python/setup.py nor setup.py found"
+            exit 1
+          fi
+      
+          sed -i 's|https://oaitriton.blob.core.windows.net/public/llvm-builds/|https://llvm.fla-org.com/|g' "$file_path"
+          grep "llvm.fla-org.com" "$file_path" || (echo "URL replacement failed"; exit 1)
 
 
       - name: Build wheels
